name = "getbarcodes"
pages_build_output_dir = "./dist"
compatibility_date = "2024-10-29"
compatibility_flags = [ "nodejs_compat_v2" ]

[[d1_databases]]
binding = "DB"
database_name = "getbarcodes"
database_id = "c6cdce76-ea1d-4ddd-b2c1-9b78d969af47"
